# Generated by Django 5.2.6 on 2025-09-11 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntraUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entra_user_id', models.CharField(max_length=36, unique=True)),
                ('upn', models.EmailField(max_length=254, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='assigned_upn',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='entra_user_id',
        ),
        migrations.AddField(
            model_name='assignment',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='assignment',
            name='entra_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='inventory.entrauser'),
        ),
    ]
