# Generated by Django 5.2.6 on 2025-09-17 13:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_entrauser_remove_assignment_assigned_upn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrauser',
            name='deleted_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='assigned_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
