# Generated by Django 5.2.6 on 2025-09-17 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_entrauser_deleted_at_alter_assignment_assigned_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('Operational', 'Operational'), ('Maintenance', 'Maintenance'), ('Decommissioned', 'Decommissioned'), ('Lost/Damaged', 'Lost/Damaged'), ('Pending Setup', 'Pending Setup'), ('Reserved', 'Reserved')], default='Operational', max_length=20),
        ),
    ]
