# Generated by Django 5.2.6 on 2025-10-01 08:44

from django.db import migrations


def create_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    for group_name in ['Admin', 'Editor', 'Viewer']:
        Group.objects.get_or_create(name=group_name)

class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_asset_status'),
    ]

    operations = [
        migrations.RunPython(create_groups),
    ]