# Generated by Django 5.2.8 on 2025-11-14 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_osoption_alter_assignment_entra_user_asset_os'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='os',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.osoption', verbose_name='OS'),
        ),
    ]
